version: '2.4'

services:
  cors_anywhere:
    image: your-image-registry/planner-cors:latest
    build:
      context: .
    tty: true
    ports:
      - '8081:8081'
    healthcheck:
      disable: true